sudo: required
language: node_js
node_js:
  - 'stable'
cache:
directories:
  - node_modules
services:
  - docker
before_install:
  - docker build -t chubi/docker-react -f Dockerfile.dev .

scripts:
  - docker run chubi/docker-react npm run test -- -- coverage