sudo: required
# language: node_js
# node_js:
#   - 'stable'
# cache:
# directories:
#   - node_modules
services:
  - docker
before_install:
  - docker build -t docker-react -f Dockerfile.dev .

# script:
#   - docker run docker-react npm run test -- -- coverage
script:
  - docker run -e CI=true docker-react npm run test
